environment: local

postgres:
  host: localhost
  port: 5432
  sslmode: disable

redis:
  host: localhost
  port: 6379
  cacheTTL: 10s
  streamKey: my_stream
  group: my_group
  consumer: my_consumer

http:
  host: 0.0.0.0
  port: 8080
  readTimeout: 5s
  writeTimeout: 5s
  maxHeaderBytes: 1048576
