environment: production

postgres:
  host: prod-db.local
  port: 5432
  sslmode: require

redis:
  host: prod-redis.local
  port: 6379
  cacheTTL: 30s
  maxAttempts: 5
  deadLetterStream: my_stream_dl

http:
  port: 80
  readTimeout: 15s
  writeTimeout: 15s
